services:
  - type: web
    name: ragbot
    env: python
    buildCommand: ""
    startCommand: streamlit run index.py --server.port=8080 --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
